### ISSUE TITLE
Use "shelved as"?

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#58] opened 2023-12-14 15:11 UTC
@Gomismis in her report on problem specimens in Botany, mentioned an example of multiple species on the same herbarium sheet. Equally, a species could have been re-identified at some point (or could be, following digitisation) and its location within the collection may not have been changed at that point. As being able to locate specimens depends on the specimens being filed under their correct name, in the above examples there may be difficulty locating the specimen. Would it not be a good idea, when using the front of folders to get taxon information, to indicate in Specify that these are the names that the specimens are filed under? This would be especially useful if a specimen has been reidentified multiple times. Finding it in the collection, you need to know which name to look under. So my proposal is - would collection managers and curators be happy if against the taxon determination in Specify, we always indicate that this is the name it is filed under? There is already an existing field in Specify for NHMD vascular plants we could use for this purpose.

**Comment by chelseagraham** [comment] 2024-03-08 12:57
Based on the discussion recorded by @RebekkaML in her notes from 29 February DaSSCo Catch-up Meeting (https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/77#issuecomment-1985301821) a tickbox to indicate where a specimen is stored is desired.

**Comment by PipBrewer** [comment] 2024-03-14 12:41
This has been implemented for NHMD in Specify already, but needs adding to the Digi App GREL script

**Comment by chelseagraham** [comment] 2024-09-05 10:48
@PipBrewer was this resolved in the Herbarium Group? (I know that it is something that we discussed in the Pinned Insect group catch up in June and then you followed up with an email with that group.)

**Comment by PipBrewer** [comment] 2024-09-12 14:08
This has been implemented in Specify for NHMD Botany, NHMA and AU:
NHMD Botany: https://github.com/NHMDenmark/DanSpecify/issues/272 
NHMA: https://github.com/NHMDenmark/DanSpecify/issues/276 
AU: https://github.com/NHMDenmark/DanSpecify/issues/274

I cannot see a ticket in Github regarding changes to the GREL script. @beckerah can you see this in the script and in the final spreadsheets for workbench importing.

I know we need to fix things for previous imports (https://github.com/NHMDenmark/Mass-Digitizer/issues/510).

**Comment by beckerah** [comment] 2024-09-13 09:31
> I cannot see a ticket in Github regarding changes to the GREL script. @beckerah can you see this in the script and in the final spreadsheets for workbench importing.

Yes, I see where the script is adding a column "storedunder" with an auto-filled value of True, and I've confirmed that it exists on a recently processed spreadsheet. Looks like @AstridBVW updated it as part of [NHMDenmark/Mass-Digitizer#490](https://github.com/NHMDenmark/Mass-Digitizer/issues/490).

**Comment by PipBrewer** [comment] 2024-09-16 14:15
Awesome thanks @beckerah !

**Closed** 2024-09-16 14:15 UTC
Labels: enhancement, NHMD, workflow, data entry, training
