### ISSUE TITLE
Fill in author name for Boxes 1-285 at Herbarium C

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Herbarium-Sheets-workstation#74] opened 2024-02-22 12:36 UTC
Please fill in author name for folders 1-285 at Herbarium C using the spreadsheet Jan has created and I have saved here:

N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Herbarium/authorDropdown.xlsx

Please work on the Herbarium laptop that is not assigned to the barcoding workstation. 
Please save the document locally on the Herbarium laptop at the beginning of a session and work locally within the collection.
Please save your upload your progress at the end of the day back to 
N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/Herbarium/authorDropdown.xlsx
If there is no option in the dropdown that corresponds to the information on the folder, please leave the Author drop down column empty and enter the correct information into the Notes column.

**Comment by RebekkaML** [comment] 2024-02-23 15:06
I started filling in the Author names sheet today and have several question / possible issues relating to that:

- some species appear on folders, but not in the sheet. The entries are in Specify, so they were not forgotten during digitization. How should we handle this? Attach them at the end of the document?

- sometimes the author name is written slightly differently on the folder than it appears on the sheet ( e.g. Raf. / Rafin). It seems obvious that it is the same person, but for now I still chose the probable answer from the dropdown menu, but added the other writing in the comments to be safe. Should we continue like this or can we be sure it is the same author and the way of abbreviating etc. doesn't play a role?

- In the sheet, there is also a list for author names of genus. On most folders, there is only the author for the species given, and in the few cases where the folder was only determined to Genus level, no author is given. Therefore, we cannot fill in most of that Genus list from looking at the folders.

- in the beginning, variants / forma species etc. were ignored during the barcoding process and only the species name was entered into the DigiApp. On most of these folders, the author is given for both the species and the subspecies etc., so we can enter it into the table. But all the lower determinations are ignored in Specify. Should we change this at some point?

- some species were assigned to the wrong box, both in the author names table and in Specify, probably due to an error during barcoding. I've created a separate issue #76 for the case I found, but we might find this again.

**Comment by jlegind** [comment] 2024-02-26 09:02
> I started filling in the Author names sheet today and have several question / possible issues relating to that:
> 
> * some species appear on folders, but not in the sheet. The entries are in Specify, so they were not forgotten during digitization. How should we handle this? Attach them at the end of the document?
> * some folders don't have an author name, and the sheets inside have different author names/no author or even different species. For these cases, I wrote "no author" in the comment field for now.
> * sometimes the author name is written slightly differently on the folder than it appears on the sheet ( e.g. Raf. / Rafin). It seems obvious that it is the same person, but for now I still chose the probable answer from the dropdown menu, but added the other writing in the comments to be safe. Should we continue like this or can we be sure it is the same author and the way of abbreviating etc. doesn't play a role?
> * In the sheet, there is also a list for author names of genus. On most folders, there is only the author for the species given, and in the few cases where the folder was only determined to Genus level, no author is given. Therefore, we cannot fill in most of that Genus list from looking at the folders.
> * in the beginning, variants / forma species etc. were ignored during the barcoding process and only the species name was entered into the DigiApp. On most of these folders, the author is given for both the species and the subspecies etc., so we can enter it into the table. But all the lower determinations are ignored in Specify. Should we change this at some point?
> * some species were assigned to the wrong box, both in the author names table and in Specify, probably due to an error during barcoding. I've created a separate issue [Herbarium sheets assigned to wrong storage box in Specify #76](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/76) for the case I found, but we might find this again.

These replies are off the top of my head. Please check with Pip.

Item 1: Assuming that names on the folder signify the same name on every sheet. I suggest to apply author name if any. Otherwise leave it blank.
Item 2: If no author name is present just leave the field blank. That is well self explanatory IMHO.
Item 3: Honestly I don't know. My gut feeling is that we want as much data as possible, yet fidelity is also very important. There needs to be a management decision on this.
Item 4: Again, I do not have a solid suggestion here. Should there be a genus author (folder) and species authors (sheets) you could add author name to both. I think you should explain this to Pip in a meeting. 
Item 5: The spreadsheet utility was designed for genus and species only. Subspecies can be added, but that is a management decision.
Item 6: Incorrectly assigned storage sounds like something that should be fixed through Specify. If this is a wider problem it warrants an investigation of the workflow.

I hope this is helpful.

**Comment by Gomismis** [comment] 2024-02-27 15:43
I just had a thought. Has anyone asked if the collection managers confirmed the trustworthiness of the author names on the folders?

**Comment by JesperMJensen** [comment] 2024-02-28 08:51
Box 186 contains 
"_Bidens connata_ Mühlbg.
Specimens: NHMD00940151 - NHMD00940156

**Comment by RebekkaML** [comment] 2024-02-28 08:59
By Item 1 ("some species appear on folders, but not in the sheet. The entries are in Specify, so they were not forgotten during digitization. How should we handle this? Attach them at the end of the document?") I mean species that appear on a folder but are not listed in the spreadsheet, such as the _Bidens connotata_ example Jesper mentioned. How should we proceed with these cases?

**Comment by RebekkaML** [comment] 2024-02-28 09:39
Also, Boxes 202 - 215 are missing entirely from the spreadsheet.

**Comment by PipBrewer** [comment] 2024-02-28 14:51
Could someone check whether these are in Specify or if the spreadsheets have not yet been imported?

**Comment by PipBrewer** [comment] 2024-02-28 15:17
@jlegind Do you have any idea why the example Jesper provided above is  not in the author database?

**Comment by PipBrewer** [comment] 2024-02-28 15:21
**COMMENT IN PROGRESS - PB ADDING AT MOMENT - give me a half an hour**


Issue 1
RML: some species appear on folders, but not in the sheet. The entries are in Specify, so they were not forgotten during digitization. How should we handle this? Attach them at the end of the document?
JKL: Assuming that names on the folder signify the same name on every sheet. I suggest to apply author name if any. Otherwise leave it blank.
PB: 

Issue 2
RML: some folders don't have an author name, and the sheets inside have different author names/no author or even different species. For these cases, I wrote "no author" in the comment field for now.
JKL: If no author name is present just leave the field blank. That is well self explanatory IMHO.
PB: 

Issue 3
RML: sometimes the author name is written slightly differently on the folder than it appears on the sheet ( e.g. Raf. / Rafin). It seems obvious that it is the same person, but for now I still chose the probable answer from the dropdown menu, but added the other writing in the comments to be safe. Should we continue like this or can we be sure it is the same author and the way of abbreviating etc. doesn't play a role?
JKL: Honestly I don't know. My gut feeling is that we want as much data as possible, yet fidelity is also very important. There needs to be a management decision on this.
PB:

Issue 4
RML: In the sheet, there is also a list for author names of genus. On most folders, there is only the author for the species given, and in the few cases where the folder was only determined to Genus level, no author is given. Therefore, we cannot fill in most of that Genus list from looking at the folders.
JKL: Again, I do not have a solid suggestion here. Should there be a genus author (folder) and species authors (sheets) you could add author name to both. I think you should explain this to Pip in a meeting.
PB: 

Issue 5
RML: in the beginning, variants / forma species etc. were ignored during the barcoding process and only the species name was entered into the DigiApp. On most of these folders, the author is given for both the species and the subspecies etc., so we can enter it into the table. But all the lower determinations are ignored in Specify. Should we change this at some point?
JKL: The spreadsheet utility was designed for genus and species only. Subspecies can be added, but that is a management decision.
PB:

Issue 6
RML: some species were assigned to the wrong box, both in the author names table and in Specify, probably due to an error during barcoding. I've created a separate issue
https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/76 for the case I found, but we might find this again.
JKL: Incorrectly assigned storage sounds like something that should be fixed through Specify. If this is a wider problem it warrants an investigation of the workflow.
PB:

**Comment by jlegind** [comment] 2024-02-29 08:14
> Box 186 contains "_Bidens connata_ Mühlbg. Specimens: NHMD00940151 - NHMD00940156 Species not in list

Real quick - the name "Bidens connata" does not yield any results through the Specify interface when taxon -> genus -> "Bidens" and

**Comment by jlegind** [comment] 2024-02-29 08:17
The range NHMD00940151 - NHMD00940156 has the name "Bidens cernua" exclusively.

**Comment by jlegind** [comment] 2024-02-29 08:19
> @jlegind Do you have any idea why the example Jesper provided above is not in the author database?
@PipBrewer 
That name with the author is in the app taxonomy but not in the spreadsheet utility because that name was not applied to any specimens yet processed through the Digi app.

**Comment by RebekkaML** [comment] 2024-02-29 08:21
> > @jlegind Do you have any idea why the example Jesper provided above is not in the author database?
> > @PipBrewer
> > That name with the author is in the app taxonomy but not in the spreadsheet utility because that name was not applied to any specimens yet processed through the Digi app.

This was then probably a mistake during digitization, where someone forgot to change the species name in the DigiApp

**Comment by PipBrewer** [comment] 2024-02-29 14:30
> > > @jlegind Do you have any idea why the example Jesper provided above is not in the author database?
> > > @PipBrewer
> > > That name with the author is in the app taxonomy but not in the spreadsheet utility because that name was not applied to any specimens yet processed through the Digi app.
> 
> This was then probably a mistake during digitization, where someone forgot to change the species name in the DigiApp

So just add the corrected name to the Notes for those boxes

**Comment by RebekkaML** [comment] 2024-03-01 14:39
I filled in the author list up to 269 today. 

Additionally to Box 202 - 215, also Nr. 252 - 267 and 269 were not in the Author spreadsheet. I listed the species and authors of those boxes in a separate table now and put it on the N-Drive as well. In a few folders, only 1 species was missing from the spreadsheet, I added those to that table as well. 

[Author list_missing entries.xlsx](https://github.com/NHMDenmark/Herbarium-Sheets-workstation/files/14462398/Author.list_missing.entries.xlsx)

It is here on the N-Drive: N:\SCI-SNM-DigitalCollections\DaSSCo\Workflows and workstations\Herbarium\Author list_missing entries.xlsx

**Comment by jlegind** [comment] 2024-03-04 11:33
@chelseagraham @PipBrewer 
There is now a spreadsheet utility specifically for the boxes range 202 to 215.
[Author backfill directory](https://github.com/NHMDenmark/Mass-Digitizer/tree/main/Author_backfill)

**Comment by jlegind** [comment] 2024-03-04 12:40
Update: The repo has a new author backfill utility for the box range 202 -215 :
https://github.com/NHMDenmark/Mass-Digitizer/blob/main/Author_backfill/authorDropdown_box202_215.xlsx

**Comment by jlegind** [comment] 2024-03-05 14:20
Regarding the boxes 252 -267 & 269: They contain the following names
- Lycodontis afer
- Anguilla anguilla
- Haemulon aurolineatum
**None of these names exist in the Digi app taxonomy** .

**Comment by FedorSteeman** [comment] 2024-03-05 14:47
@jlegind You are pulling in storage records from different disciplines/collections. You need to mind the taxontreedefid foreign key if you want to limit your search to botany, for which it is 13. The taxon tree for ichthyology has primary key 17.

**Comment by jlegind** [comment] 2024-03-06 10:17
@FedorSteeman Thanks Fedor. Your query does not return any rows (as expected) because these boxes are not under Botany.

**Comment by RebekkaML** [comment] 2024-03-07 12:01
I finished the author spreadsheet and also the utility sheet for boxes 202 - 215 today.

**Comment by chelseagraham** [comment] 2024-03-08 12:50
@JesperMJensen Will you please investigate these lingering issues?

**Comment by JesperMJensen** [comment] 2024-03-12 11:52
It seems that box 252-265 is in the following files in N:\SCI-SNM-DigitalCollections\DaSSCo\DigiApp\Data\1.Exported files from App:
NHMD_Herba_20231114_16_00_RL_corrected
NHMD_Herba_20231115_16_16_SS_corrected

They also appear in 2.PostProcessed_openRefine, but not 3.Imported specify, so it appears they have been checked, post-processed but not imported to specify.

**Comment by jlegind** [comment] 2024-03-19 12:10
Astrid imported the two files that Jesper mentioned.

**Comment by chelseagraham** [comment] 2024-03-20 09:19
Great! @JesperMJensen does that wrap up that, or are there any other problems still to be resolved?

**Comment by JesperMJensen** [comment] 2024-03-26 09:14
> Great! @JesperMJensen does that wrap up that, or are there any other problems still to be resolved?

There are still a few things. I am talking to Pip.

**Comment by chelseagraham** [comment] 2024-04-10 11:57
Have added Rebekka to tie up loose ends upon hand-over from Jesper.

**Comment by RebekkaML** [comment] 2024-04-19 12:40
Discussed with Pip on data meeting 17.04.2024.

The plan is to go through the digitized boxes again and add all subspecies /forma etc. taxa to the author spreadsheet, together with the first and last barcodes in that folder. We will also add a column called "new taxon", where everything that is already under that name in Specify can be set to "TRUE", while the newly added subspecies etc. will be set to "FALSE". 
I will be in Priorparken on Wednesday, 24.04.2024, to begin this.

For the smaller issues like writing of author names etc. I will ask Bhupjit how we should treat this.

**Comment by RebekkaML** [comment] 2024-05-01 13:29
since this ticket is getting long and complicated and was originally only intended for filling in the author name spreadsheet, which is finished for now, I have created new tickets for all the remaining issues and am closing this one.

Remaining issues:

- Sort out the 3 author sheets we currently have and ideally merge them into 1: #93  
- Different authors or different abbreviations for the same author: #90 
- No Genus names on Herbarium folders: #92 
- No subspecies, forma, variety etc. recorded in boxes 1-285: #91

**Closed by RebekkaML** 2024-05-01 13:29 UTC
Labels: NHMD, data entry

**Comment by RebekkaML** [comment] 2025-01-15 14:04
Here is a copy of the completed author names spreadsheet (merged from the 3 separate ones):

[authorDropdown_completed.xlsx](https://github.com/user-attachments/files/18425600/authorDropdown_completed.xlsx)
